### ISSUE TITLE
Stickers not showing up in new products widget

### ISSUE THREAD

**Issue by hakkim** [WaPoNe/module-stickers#5]
Magento version : 2.1.7

Steps to reproduce : 
1) Installed WaPoNe/module-stickers manually
2) enabled the extension
3) discount calculation : automatic
4) created a cms page with new products list

Expected result : Discount sticker must be shown anywhere inside the product list block

Actual result : Discount sticker is not showing up

It is working well with category page and product listing widget... Could you please have a look at this issue?

**Comment by WaPoNe** [comment]
Issue solved with 0.0.4 version
Thank you @hakkim
